### ISSUE TITLE
Code of Conduct and Contribution Guidelines

### ISSUE THREAD

**Issue by codefriar** [PetriPod/PetriPod#3]
Team, 

Let's establish a code of conduct, and some contribution guidelines.

Ideally, I'd like the first to cover the basics of *don't be a jerk* and the later to cover in depth docs of how to submit a PR, what the process for review is, and who/when do contributors become maintainers etc.

Thoughts?

**Comment by ghost** [comment]
I'll establish some clauses, regarding conduct, in the morning, and add it to the wiki, once everyone is happy with it.

I request assistance from all team members regarding contribution guidelines.
Once I have all required information, I can draft something up, and everyone can look over it

**Comment by ghost** [comment]
I have added the code of conduct to the Wiki.

Any issues, please post here. Happy to hear everyones thoughts
Link: https://github.com/PetriPod/PetriPod/wiki/Code-of-Conduct

@denis-ev @codefriar @evanmn @kpoppel

**Comment by codefriar** [comment]
@voryzen  has put together a nice code of conduct document, but I'd really like each of us to read, submit tweaks and ultimately 'sign off' in a comment here. 

Thoughts?

**Comment by ghost** [comment]
@denis-ev @kpoppel @evanmn 

Once everyone has a look, I'll concentrate on the contribution guidelines.

**Comment by denis-ev** [comment]
Just did a quick read over the code of conduct.
I like it.

**Comment by kpoppel** [comment]
Looks good to me too.

**Comment by ghost** [comment]
Same goes for me

**Comment by codefriar** [comment]
I agree to this code of conduct.

**Comment by voryzen** [comment]
That's goes without saying, I agree to this code of conduct.

Now on to the guidelines . I'll start it Friday afternoon

**Comment by buxel** [comment]
@voryzen i also agree to this CoC.

**Comment by ghost** [comment]
Contribution guidelines are up.
@codefriar @denis-ev @evanmn @kpoppel

**Comment by ghost** [comment]
New acceptance of CoC issue up
@codefriar @denis-ev @evanmn @kpoppel

**Comment by ghost** [comment]
@voryzen Both documents look good, although the contribution guidelines I would put in CONTRIBUTING.md, either in the root of the repo or /docs/CONTRIBUTING.md. /docs/ is where github pages is served from. I would also just imply concent to both documents when someone contributes, rather than have everyone explicitly accept in an issue. 

Along with the contributing guidelines, it would be good to lay out issue templates for feature requests, package requests, and issues.

**Comment by ghost** [comment]
@evanmn Thanks for the feedback, I'm glad you like it, but I do have you covered where the implied consent is concerned. there is a clause referring to impled agreement in the code of conduct, down the bottom of that document (from memory); you just gotta read it.
@codefriar wanted the community leaders/ founders of this project to consent to the code of conduct explicitly, as they would be the 'moderators' of the community. I can see his point, I have implemented that, and have requested you all to accept, as such.

This is obviously still up for discussion, but I would feel better if Kev had some input where your suggestion is concerned, rather than just removing what has been put in place. He is the Daddy of PetriPod, of sorts.

As far as the CONTRIBUTING.md file goes, I'll see what works best for the website, before I start manipulating more code. I believe the website needs a separate github repo, so once that is sorted, we can finalise file locations further.

Your template idea is recognised, and I agree that it would help streamline work. I already have a 'services' documentation template, that i wrote (originally for the previous project we worked on but it was never implemented there) which I plan to use for PetriPod.

I have no issues with creating a mock up of this, if you could take a look at it when I've finished; that would be very much appreciated
